/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.moquality;

import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import io.appium.java_client.android.AndroidDriver;
import java.net.URL;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    private static AndroidDriver<WebElement> driver;

    @BeforeClass public static void setUp() throws Exception {

        // Set desired capabilities.
        DesiredCapabilities capabilities = new DesiredCapabilities();

        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("deviceName", "Device");
        capabilities.setCapability("app", "path_to_apk");
        capabilities.setCapability("appWaitActivity", "*");
        capabilities.setCapability("automationName", "UiAutomator2");
        capabilities.setCapability("autoGrantPermissions", true);
        capabilities.setCapability("fullReset", true);

        // Open the app.
        driver = new AndroidDriver<WebElement>(new URL("http://localhost:4723/wd/hub"), capabilities);

    }

    @AfterClass public static void tearDown() {
        driver.quit();
    }

    @Test public void testLaunchApp() {
        driver.launchApp();
    }
}
